### ISSUE TITLE
Skill Exp Cards

### ISSUE THREAD

**Issue by katmeww** [DarkEnergyProcessor/NPPS4#12]
///Note!! you may know about many of these things already. These are just reminders with a bit of context to help out.\\\

-Skill Exp Cards: Context: skill exp cards consist of moms (URs) https://llsif.fandom.com/wiki/Idols%27_Mothers , purple (SSRs) , classmates (SRs) and yazawa kids (R's) currently only yazawa kids and I think classmates are obtainable through Live chest awards. To obtain all of them players will need a scouting banner, or exchange for them through sticker shop & point shop. (Shop -> Sticker Shop or Shop -> Point Shop) Credit to r0dr4t for skill exp reminder! In regard to the scouting banner, players were forced to use blue tickets to get skill exp, which was exchangeable through the Sticker Shop. 

Thank you auahdark. <3

**Comment by MikuAuahDark** [comment]
For now, support units can be obtained through serial codes. 1fd7c161eff56de2ec57aed33c52660d8dda68c8

The serial code is: https://youtu.be/Qk4KcP1VGIc (yes, the URL is the serial code).
