### ISSUE TITLE
Unlocking a title via achievement appends it to your available titles before you claim it from "Goals"

### ISSUE THREAD

**Issue by Ramen2X** [DarkEnergyProcessor/NPPS4#32]
Server information:
- Host OS: Debian
- NPPS4 commit: 2189cc0 (latest in master as of writing)
- Database type: PostgreSQL

Steps to reproduce:
- Clear an achievement that awards you a title (ie: get a full combo 50 times for the FULL COMBO! title).
- Without claiming the rewards from "Goals", check your available titles.
- Observe that the title from the achievement is already present.
- Attempt to select that new title for display on your profile, resulting in an error.

Once you properly claim the title from "Goals", it becomes selectable normally with no error.

This possibly applies to Wallpapers as well, but I have not had the time to check.

**Comment by MikuAuahDark** [comment]
> Attempt to select that new title for display on your profile, resulting in an error.

Is there an exact error message for this one?

The exact goal you mentioned has no `auto_reward_flag` set. This means the respective reward must be claimed from the goals menu. I wonder if the game specialize title so that it gets claimed automatically.

**Comment by Ramen2X** [comment]
The specific error is `No such award`.
Here's a screenshot:
![image](https://github.com/user-attachments/assets/8e4b7247-06e6-47f5-a8b9-04f60272706d)

**Comment by MikuAuahDark** [comment]
Alright. What if you restart the client in that case?

**Comment by Ramen2X** [comment]
When you restart the client (which you're forced to upon receiving the error), the title is no longer shown as an option until you claim it properly.

**Comment by MikuAuahDark** [comment]
The only plausible reason why is the game specialize titles and wallpaper as "auto claim regardless of `auto_reward_flag`". It's fixable.

**Comment by Ramen2X** [comment]
This specific issue is fixed now, but there still appears to be a problem with the client/server sync when exchanging stickers for wallpapers (and possibly titles as well) in the Sticker Shop. I didn't notice this until now.

When you exchange stickers for a wallpaper, it won't appear in your available wallpapers until you restart the client. It doesn't appear in your present box either.

I noticed in commit 3023e58 you intentionally bypassed the present box for wallpapers and titles exchanged in the Sticker Shop, but it doesn't seem like the client immediately recognizes them as claimed when appended directly to your account like this.

Check the below (abridged for time) video for a demonstration.

https://github.com/user-attachments/assets/4c44bd75-a940-45d7-af99-be31c0be8a58

I wasn't sure whether to open a new ticket for this, but it's very similar to this issue so I'll put it here. Apologies in advance if this is the wrong place for this.

**Comment by MikuAuahDark** [comment]
Hmm, weird. I have conflicting report about it where it result in same symptom as the original issue. I probably have to revert that, thanks.
